//! Embeds `conformance/scenarios/*.yaml` and mints one test per scenario.
//!
//! Two generated files:
//!   * `scenario_files.rs` — `FILES: &[(name, include_str!(path))]`, built
//!     from the directory listing so a new fixture file is embedded without
//!     anyone editing a list.
//!   * `scenario_tests.rs` — one `conformance_test!` invocation per scenario,
//!     named `<file>_<scenario>`, so `cargo test` and the browser runner
//!     report each scenario individually, the way pytest's parametrize does.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = Path::new(&manifest)
        .join("../../conformance/scenarios")
        .canonicalize()
        .expect("conformance/scenarios exists");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files: Vec<_> = fs::read_dir(&dir)
        .unwrap()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "yaml"))
        .collect();
    files.sort();

    let mut list = String::from(
        "/// Every `conformance/scenarios/*.yaml`, embedded. Generated by build.rs from the directory listing.\n\
         pub const FILES: &[(&str, &str)] = &[\n",
    );
    let mut tests =
        String::from("// @generated by build.rs: one test per scenario. Do not edit.\n");
    for path in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path.file_name().unwrap().to_str().unwrap();
        let stem = path.file_stem().unwrap().to_str().unwrap();
        list.push_str(&format!(
            "    ({name:?}, include_str!({:?})),\n",
            path.display()
        ));
        let text = fs::read_to_string(path).unwrap();
        let doc: serde_norway::Value =
            serde_norway::from_str(&text).unwrap_or_else(|e| panic!("{name}: {e}"));
        let scenarios = doc["scenarios"]
            .as_sequence()
            .unwrap_or_else(|| panic!("{name}: no `scenarios` list"));
        for sc in scenarios {
            let sname = sc["scenario"]
                .as_str()
                .unwrap_or_else(|| panic!("{name}: a scenario has no name"));
            tests.push_str(&format!(
                "conformance_test!(fn {}_{}() {{ aloelite_conformance::runner::run_scenario({name:?}, {sname:?}); }});\n",
                ident(stem),
                ident(sname)
            ));
        }
    }
    list.push_str("];\n");

    let out = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out).join("scenario_files.rs"), list).unwrap();
    fs::write(Path::new(&out).join("scenario_tests.rs"), tests).unwrap();
}

fn ident(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}
