#!/usr/bin/env python3
"""Regenerate conformance/vectors/format-v1.json from the reference implementation.

Run from the repo root:  python script/gen_format_vectors.py

Every value here is DERIVED, never invented: the inputs are fixed constants
chosen for coverage (empty, one byte, chunk-aligned, chunk-aligned+1, binary),
and the outputs come from aloelite.crypto / aloelite.db. Regenerating should be
a no-op diff. A non-empty diff means the on-disk format changed, which is
exactly when you want a review — see conformance/vectors/README.md.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from aloelite import crypto  # noqa: E402
from aloelite.db import chunk_hash, split_chunks  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "conformance/vectors/format-v1.json"

# Fixed inputs. uuid7-shaped ids and a 32-byte key, written out literally so a
# port can paste them in without needing our id generator or a CSPRNG.
VOLUME_ID = "0195f0a1-2b3c-7def-8000-0123456789ab"
ROOT_NODE_ID = "0195f0a1-2b3c-7def-8001-fedcba987654"
VOLUME_KEY = bytes.fromhex("00112233445566778899aabbccddeeff" "ffeeddccbbaa99887766554433221100")
TOKEN = bytes.fromhex("0f1e2d3c4b5a69788796a5b4c3d2e1f0")
MOUNT_NONCE = bytes.fromhex("a0a1a2a3a4a5a6a7a8a9aaabacadaeaf")

PAYLOADS = [
    ("empty", b""),
    ("one-byte", b"\x00"),
    ("ascii", b"hello"),
    ("binary-high", bytes(range(256))),
    ("chunk-aligned", b"\xab" * 64),
    ("chunk-aligned-plus-one", b"\xab" * 65),
]


def h(b: bytes) -> str:
    return b.hex()


def main() -> None:
    doc: dict = {
        "format": "aloelite-format-vectors",
        "version": 1,
        "note": "generated by script/gen_format_vectors.py; see README.md",
        "constants": {
            "nonce_len": crypto.NONCE_LEN,
            "tag_len": crypto.TAG_LEN,
            "token_len": crypto.TOKEN_LEN,
            "mount_nonce_len": crypto.MOUNT_NONCE_LEN,
            "argon2_time_cost": crypto.ARGON2_TIME_COST,
            "argon2_memory_cost_kib": crypto.ARGON2_MEMORY_COST,
            "argon2_parallelism": crypto.ARGON2_PARALLELISM,
            "argon2_key_len": crypto.ARGON2_KEY_LEN,
        },
        "inputs": {
            "volume_id": VOLUME_ID,
            "root_node_id": ROOT_NODE_ID,
            "volume_key": h(VOLUME_KEY),
            "token": h(TOKEN),
            "mount_nonce": h(MOUNT_NONCE),
        },
    }

    # CV-2: the content address folds the byte length in, so a short chunk can
    # never collide with a full chunk sharing leading bytes.
    doc["chunk_address"] = [
        {"name": name, "bytes": h(data), "chunk_hash": chunk_hash(data)}
        for name, data in PAYLOADS
    ]

    # CV-1: uniform chunking, short final chunk, empty => zero chunks.
    doc["chunk_split"] = [
        {"size": size, "chunk_size": cs, "lengths": [len(c) for c in split_chunks(b"z" * size, cs)]}
        for size, cs in [(0, 8), (1, 8), (8, 8), (9, 8), (24, 8), (25, 8), (1000, 64)]
    ]

    # ENC-2 key ladder.
    h_v = crypto.volume_hash(VOLUME_ID, ROOT_NODE_ID)
    doc["volume_hash"] = [
        {"volume_id": VOLUME_ID, "root_node_id": ROOT_NODE_ID, "h_v": h(h_v)}
    ]

    # Argon2id is deliberately expensive; two vectors is enough to pin the
    # work factors, and a port that gets them wrong fails both.
    doc["unlock_key"] = [
        {"pin_utf8": pin.decode(), "h_v": h(h_v), "k_u": h(crypto.derive_unlock_key(pin, h_v))}
        for pin in (b"correct horse", b"")
    ]

    cipher = crypto.ChunkCipher(VOLUME_KEY, VOLUME_ID, convergent=True)
    doc["chunk_key"] = [
        {"volume_key": h(VOLUME_KEY), "volume_id": VOLUME_ID, "k_chunk": h(cipher._k)}
    ]

    # The dedup-critical vector: convergent encryption must be byte-identical
    # across implementations or the same plaintext lands at two addresses.
    doc["encrypt_chunk_convergent"] = []
    for name, data in PAYLOADS:
        ct, nonce, tag = cipher.encrypt_chunk(data)
        doc["encrypt_chunk_convergent"].append(
            {
                "name": name,
                "plaintext": h(data),
                "n_c": h(nonce),
                "ciphertext": h(ct),
                "tag": h(tag),
                "chunk_hash": chunk_hash(ct),
            }
        )

    # Unwrap is the deterministic direction of the seal (wrap picks a random
    # nonce), so the vector fixes a wrapped blob and asserts what opens out.
    k_u = bytes.fromhex(doc["unlock_key"][0]["k_u"])
    wrapped, wrap_nonce = crypto.wrap_volume_key(k_u, VOLUME_KEY)
    doc["unwrap_volume_key"] = [
        {
            "k_u": h(k_u),
            "wrapped_key": h(wrapped),
            "wrap_nonce": h(wrap_nonce),
            "volume_key": h(VOLUME_KEY),
        }
    ]

    doc["session_kek"] = [
        {
            "token": h(TOKEN),
            "mount_nonce": h(MOUNT_NONCE),
            "kek": h(crypto.session_kek(TOKEN, MOUNT_NONCE)),
        }
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}")


if __name__ == "__main__":
    main()
