//! Generates `templates.rs` from `aloelite/config/sql-templates.yaml`.
//!
//! The YAML is the single source of truth for every implementation; this
//! turns its sixty statements into `const &str`s at build time so a template
//! name is checked by the compiler rather than looked up at run time, and so
//! the shipped engine carries no YAML parser. Groups become modules,
//! `resolve_segment` becomes `resolution::RESOLVE_SEGMENT`.
//!
//! Only groups that carry executable `sql` are emitted (the reference's
//! `_SQL_GROUPS`); `host_only` and `meta` are prose and version.

use std::env;
use std::fs;
use std::path::Path;

const SQL_GROUPS: &[&str] = &[
    "resolution",
    "mutation",
    "validation",
    "recursive",
    "maintenance",
];

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let repo = Path::new(&manifest).join("../..");
    let yaml_path = repo.join("aloelite/config/sql-templates.yaml");
    println!("cargo:rerun-if-changed={}", yaml_path.display());

    let text = fs::read_to_string(&yaml_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", yaml_path.display()));
    let doc: serde_norway::Value =
        serde_norway::from_str(&text).expect("sql-templates.yaml parses");

    let version = doc["meta"]["version"]
        .as_u64()
        .expect("meta.version is an integer");

    let mut out = String::new();
    out.push_str(
        "// @generated by build.rs from aloelite/config/sql-templates.yaml. Do not edit.\n",
    );
    out.push_str(&format!(
        "/// `meta.version` of the template file this engine was built from.\npub const VERSION: u32 = {version};\n\n"
    ));

    for group in SQL_GROUPS {
        let entries = doc[group]
            .as_mapping()
            .unwrap_or_else(|| panic!("group {group} is a mapping"));
        out.push_str(&format!("pub mod {group} {{\n"));
        for (name, entry) in entries {
            let name = name.as_str().expect("template names are strings");
            let sql = entry["sql"]
                .as_str()
                .unwrap_or_else(|| panic!("{group}.{name} has a string `sql`"));
            let consumed_by = entry["consumed_by"]
                .as_sequence()
                .map(|s| {
                    s.iter()
                        .filter_map(|v| v.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .unwrap_or_default();
            let konst = name.to_uppercase();
            out.push_str(&format!(
                "    /// `{group}.{name}` — consumed by: {consumed_by}\n    pub const {konst}: &str = {sql:?};\n"
            ));
        }
        out.push_str("}\n\n");
    }

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("templates.rs");
    fs::write(&dest, out).expect("write templates.rs");
}
